{ lib, pkgs, config, options, ... }:

let
  cfg = config.hub.localNetwork;
  markerStart = "# >>> nixos-config local-network >>>";
  markerEnd = "# <<< nixos-config local-network <<<";

  renderHostLine = ip: names: "${ip} ${lib.concatStringsSep " " names}";

  renderedEntries = lib.concatStringsSep "\n" (lib.mapAttrsToList renderHostLine cfg.entries);

  entriesFile = pkgs.writeText "local-network-hosts" renderedEntries;
  tailscaleAliasCommands = lib.concatStringsSep "\n" (lib.mapAttrsToList
    (alias: node: ''
      if ip="$($tailscale_bin ip -4 ${lib.escapeShellArg node} 2>/dev/null | /usr/bin/head -n1)" && [ -n "$ip" ]; then
        /usr/bin/printf '%s %s\n' "$ip" ${lib.escapeShellArg alias} >> "$tmp_entries"
      else
        echo "warning: could not resolve Tailscale node ${node} for alias ${alias}" >&2
      fi
    '')
    cfg.tailscaleAliases);
in
{
  options.hub.localNetwork = {
    entries = lib.mkOption {
      type = lib.types.attrsOf (lib.types.listOf lib.types.str);
      default = { };
      example = {
        "192.168.1.199" = [ "mele" ];
      };
      description = ''
        Static local-network host aliases keyed by IP address. These entries are
        exposed through the platform-appropriate host resolution mechanism so the
        same alias data can be reused across Darwin and non-Darwin hosts.
      '';
    };

    tailscaleAliases = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = {
        mele = "mele-hub";
      };
      description = ''
        Host aliases whose IP address should be resolved from Tailscale during
        Darwin activation. Attribute names are local aliases and values are
        Tailscale node names.
      '';
    };
  };

  config = lib.mkMerge [
    (lib.optionalAttrs (lib.hasAttrByPath [ "networking" "hosts" ] options) {
      networking.hosts = cfg.entries;
    })

    (lib.mkIf pkgs.stdenv.isDarwin {
      # nix-darwin only runs a fixed set of activation script phases. Append to
      # postActivation instead of defining a custom activationScripts key, which
      # would evaluate but never execute.
      system.activationScripts.postActivation.text = lib.mkAfter ''
        echo "merging local network host aliases into /etc/hosts..." >&2

        hosts_file=/etc/hosts
        ssh_config_file=/etc/ssh/ssh_config.d/120-local-network.conf
        tmp_clean=$(/usr/bin/mktemp -t local-network-hosts.clean)
        tmp_final=$(/usr/bin/mktemp -t local-network-hosts.final)
        tmp_entries=$(/usr/bin/mktemp -t local-network-hosts.entries)
        tmp_ssh=$(/usr/bin/mktemp -t local-network-ssh.conf)

        cleanup() {
          /bin/rm -f "$tmp_clean" "$tmp_final" "$tmp_entries" "$tmp_ssh"
        }
        trap cleanup EXIT

        if [ -f "$hosts_file" ]; then
          /usr/bin/awk -v start=${lib.escapeShellArg markerStart} -v end=${lib.escapeShellArg markerEnd} '
            $0 == start { skip = 1; next }
            $0 == end { skip = 0; next }
            skip != 1 { print }
          ' "$hosts_file" > "$tmp_clean"
        else
          : > "$tmp_clean"
        fi

        /bin/cp "$tmp_clean" "$tmp_final"
        /bin/cat ${entriesFile} > "$tmp_entries"

        tailscale_bin=
        for candidate in /opt/homebrew/bin/tailscale /usr/local/bin/tailscale /run/current-system/sw/bin/tailscale; do
          if [ -x "$candidate" ]; then
            tailscale_bin="$candidate"
            break
          fi
        done
        if [ -n "$tailscale_bin" ]; then
          ${tailscaleAliasCommands}
        else
          ${lib.optionalString (cfg.tailscaleAliases != { }) ''
            echo "warning: tailscale command not found; skipping Tailscale host aliases" >&2
          ''}
        fi

        if [ -s "$tmp_entries" ]; then
          needs_separator=
          if [ -s "$tmp_final" ]; then
            needs_separator=1
          fi

          {
            if [ -n "$needs_separator" ]; then
              printf '\n'
            fi
            printf '%s\n' ${lib.escapeShellArg markerStart}
            /bin/cat "$tmp_entries"
            printf '\n%s\n' ${lib.escapeShellArg markerEnd}
          } >> "$tmp_final"
        fi

        if [ ! -f "$hosts_file" ] || ! /usr/bin/cmp -s "$tmp_final" "$hosts_file"; then
          /bin/cp "$tmp_final" "$hosts_file"
          /bin/chmod 644 "$hosts_file"
          /usr/bin/dscacheutil -flushcache || true
          /usr/bin/killall -HUP mDNSResponder || true
        fi

        if [ -s "$tmp_entries" ]; then
          {
            printf '# Generated by nixos-config local-network; do not edit.\n'
            /usr/bin/awk '
              NF >= 2 {
                ip = $1
                for (i = 2; i <= NF; i++) {
                  printf "Host %s\n  HostName %s\n", $i, ip
                }
              }
            ' "$tmp_entries"
          } > "$tmp_ssh"
          /bin/mkdir -p /etc/ssh/ssh_config.d
          if [ ! -f "$ssh_config_file" ] || ! /usr/bin/cmp -s "$tmp_ssh" "$ssh_config_file"; then
            /bin/cp "$tmp_ssh" "$ssh_config_file"
            /bin/chmod 644 "$ssh_config_file"
          fi
        elif [ -f "$ssh_config_file" ]; then
          /bin/rm -f "$ssh_config_file"
        fi
      '';
    })
  ];
}
