baseURL = "https://example.home.behaghel.org/"
title = "example"
locale = "en"

enableRobotsTXT = true

[params]
description = "A personal static site."

[params.mele]
site = "example"
host = "hub@mele"
root = "/srv/static/example"

[params.analytics]
enable = false
provider = "goatcounter"

[params.analytics.goatcounter]
code = ""
domain = ""
script = "https://gc.zgo.at/count.js"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
