name: Flake checks

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - name: Run flake checks
        run: nix flake check --show-trace
